Use minikube in elastic-setup

diff --git a/elastic-setup b/elastic-setup
--- a/elastic-setup
+++ b/elastic-setup
@@ -1,39 +1,78 @@
-#!/bin/bash 
+#!/bin/bash
 
 APP_NAME=my-otel-demo
+
+# Define bash colors
+# Reset
+Color_Off='\033[0m'       # Text Reset
+
+# Regular Colors
+Black='\033[0;30m'        # Black
+Red='\033[0;31m'          # Red
+Green='\033[0;32m'        # Green
+Yellow='\033[0;33m'       # Yellow
+Blue='\033[0;34m'         # Blue
+Purple='\033[0;35m'       # Purple
+Cyan='\033[0;36m'         # Cyan
+White='\033[0;37m'        # White
+
+# Bold
+BBlack='\033[1;30m'       # Black
+BRed='\033[1;31m'         # Red
+BGreen='\033[1;32m'       # Green
+BYellow='\033[1;33m'      # Yellow
+BBlue='\033[1;34m'        # Blue
+BPurple='\033[1;35m'      # Purple
+BCyan='\033[1;36m'        # Cyan
+BWhite='\033[1;37m'       # White
+
+title () {
+	echo -e ${Cyan}"<[${BBlue} $1 ${Cyan}]>${Color_Off}"
+}
+
+die () {
+	echo -e "${BRed}ERROR: $1${Color_Off}"
+	exit 1
+}
+
+title "Checking environment for $APP_NAME..."
+
 # Check tools
-tools=("helm" "kubectl")
+tools=("helm" "kubectl" "minikube")
 for tool in ${tools[@]}; do
 	if ! command -v $tool 2>&1 >/dev/null
 	then
-		echo "$tool could not be found, please install both helm and kubernetes-cli"
-		exit 1
+		die "Command '$tool' could not be found, please install"
 	fi
 done
 
 if [ -z "${OTEL_EXPORTER_OTLP_ENDPOINT}" ]; then
-  echo "You must set OTEL_EXPORTER_OTLP_ENDPOINT to a valid URL!"
-  exit 1
+  die "You must set OTEL_EXPORTER_OTLP_ENDPOINT to a valid URL!"
 fi
 if [ -z "${OTEL_EXPORTER_OTLP_HEADERS}" ]; then
-  echo "You must set authorization headers for OTEL beginnig with Authorization="
-  exit 1
+  die "You must set authorization headers for OTEL beginnig with Authorization="
 fi
 
 if [[ $OTEL_EXPORTER_OTLP_HEADERS == "Authorization=*" ]]; then
-  echo "OTEL_EXPORTER_OTLP_HEADERS has invalid value \"$OTEL_EXPORTER_OTLP_HEADERS\", should start with Authorization="
-  exit 1
+  die "OTEL_EXPORTER_OTLP_HEADERS has invalid value \"$OTEL_EXPORTER_OTLP_HEADERS\", should start with Authorization="
 fi
 
 if [ -z "${OTEL_DEMO_ES_ENDPOINT}" ]; then
-  echo "You must set OTEL_DEMO_ES_ENDPOINT to a valid Elasticsearch URL"
-  exit 1
+  die "You must set OTEL_DEMO_ES_ENDPOINT to a valid Elasticsearch URL"
 fi
 
 if [ -z "${OTEL_DEMO_ES_API_KEY}" ]; then
-  echo "You must set OTEL_DEMO_ES_API_KEY"
-  exit 1
+  die "You must set OTEL_DEMO_ES_API_KEY"
 fi
+
+if minikube status | grep -q "Running"; then
+	title "Minikube is already running, skipping..."
+else
+	title "Minikube is not running, starting..."
+	minikube start --ports=80:80,443:443
+fi
+
+echo "\n\n"
 
 OTEL_ENDPOINT_NO_PROTO=`echo $OTEL_EXPORTER_OTLP_ENDPOINT | sed -r -e 's/^https?:\/\///'`
 OTEL_AUTH_VALUE=`echo $OTEL_EXPORTER_OTLP_HEADERS | cut -d= -f2-`
@@ -48,7 +87,7 @@ kubectl create secret generic elastic-secret-ds \
   --from-literal=elastic_endpoint="$OTEL_DEMO_ES_ENDPOINT" \
   --from-literal=elastic_api_key="$OTEL_DEMO_ES_API_KEY"
 
-
+title "Installing/Upgrading helm charts for $APP_NAME..."
 pushd kubernetes/elastic-helm
 helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
 helm repo update open-telemetry
@@ -69,10 +108,19 @@ helminst () {
 helminst $APP_NAME -f deployment.yaml $1 open-telemetry/opentelemetry-demo
 helminst otel-daemonset open-telemetry/opentelemetry-collector --values daemonset.yaml  
 
+# Check if dns entry for otel-demo.internal exists
+if ! grep -q "otel-demo.internal" /etc/hosts
+then
+	die 'otel-demo.internal missing from /etc/hosts, please add: "127.0.0.1 otel-demo.internal" to /etc/hosts'
+else
+	title "otel-demo.internal already in /etc/hosts!"
+fi
+
+title "Setup complete!"
 cat <<-EOF
-Otel demo is deployed with nginx ingress controller running.
+
+
 Please add the following line to your /etc/hosts file
-127.0.0.1 otel-demo.internal
 Note, that for minikube and some other kubernetes distributions you may need a different IP.
 For minikube this may be found with the 'minikube ip' command.
 
